version: '3'

services:
  cash_machine_db_data:
    image: mariadb:latest
    ports:
      - 3366:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=cashmachine
    volumes:
      - cash_machine_db_data:/var/lib/mysql:rw

volumes:
  cash_machine_db_data:
